"""Central place for all project paths.

Every notebook and module imports its paths from here, so nobody hard-codes
folder locations and the code works on every teammate's machine.
"""

from pathlib import Path


def _find_project_root(start: Path) -> Path:
    """Walk up from `start` until a folder containing environment.yml is found."""
    current = start.resolve()
    while True:
        if (current / "environment.yml").exists():
            return current
        if current.parent == current:
            # We reached the filesystem root without finding the marker file.
            raise FileNotFoundError(
                "Could not find environment.yml in any parent folder of " + str(start)
            )
        current = current.parent


# Root of the repository (the folder that contains environment.yml)
PROJECT_ROOT = _find_project_root(Path(__file__).parent)

# Original Kaggle CSVs: read-only, never modified
DATA_RAW = PROJECT_ROOT / "data" / "raw"

# Files generated by our code (gitignored)
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

# Kaggle submission files: ML_Group_41_VersionXX.csv
SUBMISSIONS = PROJECT_ROOT / "submissions"

# Homework PDF, exported figures, tables
REPORTS = PROJECT_ROOT / "reports"
